### ISSUE TITLE
Support for TLSv1.3 draft 18

### ISSUE THREAD

**Issue by ghost** [ajhaydock/BoringNginx#3] opened 2017-04-26 09:16 UTC
Would you be able to provide a patch of sorts that enables support for TLSv1.3 draft 18?

NGINX v1.13.0 is out and supports TLSv1.3. I have tried your BoringNginx script on this version, but either it doesn't support TLSv1.3 or not draft 18.

**Comment by alexhaydock** [comment] 2017-04-26 12:47
Thanks for the heads-up about v1.13.0! I've bumped the version in the repository to account for this release.

I'm having some issues with this myself, and I suspect it might be due to the BoringSSL git master currently being at draft 19, while browsers are mostly stuck on draft 18. I know there is a similar issue when compiling with OpenSSL from git.

For what it's worth, Nginx appears to boot and start properly with v1.13.0 with the following key options set:
```nginx
ssl_protocols	TLSv1.2 TLSv1.3;
ssl_ciphers	[ECDHE-ECDSA-CHACHA20-POLY1305]:[ECDHE-ECDSA-AES128-GCM-SHA256]:[ECDHE-ECDSA-AES256-GCM-SHA384];
ssl_ecdh_curve	auto;
```

Unfortunately right now I'm not able to get any browser to actually report that it is negotiating a TLS v1.3 connection with the server. I'll report back if I get this working.

**Comment by ghost** [comment] 2017-04-26 14:36
Hi Alex,

My comment is regarding for nginx configuration you shared. The ciphers are wrong. TLSv1.3 ciphers start with string TLS13-... You need to correct this to get anywhere.

I have succeeded at making openssl/nginx negotiate TLSv1.3, but I had to git clone the 1.1.1-dev TLS1_3 branch (draft 18).

**Comment by alexhaydock** [comment] 2017-04-26 15:23
Thanks for the note. I'm now testing:
```nginx
ssl_ciphers	[TLS13-ECDHE-ECDSA-CHACHA20-POLY1305]:[ECDHE-ECDSA-CHACHA20-POLY1305]:[ECDHE-ECDSA-AES128-GCM-SHA256]:[ECDHE-ECDSA-AES256-GCM-SHA384];
```

Nginx starts, so the syntax is correct, but I'm still having issues negotiating TLS v1.3 on either Chrome 58 Beta or Firefox. I'm suspecting that this might require a specific commit to be checked out from the BoringSSL repo. Either that, or it will require a patch, but putting such a patch together may be beyond my understanding of the BoringSSL codebase.

**Comment by ghost** [comment] 2017-04-26 23:01
Right. I am unfamiliar with the BoringSSL repo, whether they have a specific release/branch for TLSv1.3 draft 18. Somewhere I read that BoringSSL does support TLSv1.3.

The [wonderfall/boring-nginx](https://hub.docker.com/r/wonderfall/boring-nginx/) claims to use a patch to get TLSv1.3 working.

One more caveat.... NGINX needs to be compiled with flag `--with-openssl-opt=enable-tls1_3`.

**Comment by ghost** [comment] 2017-04-30 00:29
Alex, I am certain that my BoringNginx installation is running with TLSv1.3 draft 19.

My nginx setting
```
ssl_protocols TLSv1.2 TLSv1.3;
```
is not causing any startup errors. That's why. They key is to compile nginx with the flag `--with-openssl-opt=enable-tls1_3`.

**Comment by ghost** [comment] 2017-04-30 06:33
BoringSSL TLSv1.3 daft 18 https://github.com/google/boringssl/commit/a833c357edae4eb7f47b9808bf744bd9bb0df18d

**Comment by ReyKoxha** [comment] 2017-04-30 22:43
Anyone found a working config yet?
This is my NGINX Conf block so far:

```
	# SSL
    	ssl on;
    	ssl_certificate /etc/letsencrypt/live/------/fullchain.pem;
    	ssl_certificate_key /etc/letsencrypt/live/------/privkey.pem;
    	ssl_trusted_certificate /etc/letsencrypt/live/------/fullchain.pem;
    	ssl_session_cache shared:SSL:50m;
    	ssl_session_timeout 10m;
    	ssl_prefer_server_ciphers on;
    	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers	[TLS13-ECDHE-ECDSA-CHACHA20-POLY1305]:[ECDHE-ECDSA-CHACHA20-POLY1305]:[ECDHE-ECDSA-AES128-GCM-SHA256]:[ECDHE-ECDSA-AES256-GCM-SHA384];
	ssl_ecdh_curve	auto;
	ssl_dhparam /etc/nginx/ssl/dhparam.pem;
	resolver 8.8.8.8 8.8.4.4;
```

As @ajhaydock, I fail negotiation.

**Comment by alexhaydock** [comment] 2017-04-30 22:54
@ReyKoxha I'm going to test the `--with-openssl-opt=enable-tls1_3` build flag tomorrow, along with trying to check out some specific commits from the BoringSSL repo to see if I can get draft 18 going properly. Your config looks very similar to where I'm at currently too, though.

Thanks for locating the specific commit, @peterkahl. Looking at the blame feature for that specific line though, it would appear that the line still hasn't been changed yet in master. This leads me to think that we need to look somewhere else.

Can I ask what specifically it is that makes you certain your installation is running draft 19, @peterkahl ?

**Comment by ghost** [comment] 2017-04-30 22:55
@ReyKoxha Your nginx configuration seems fine.

nginx must be compiled with the flag `--with-openssl-opt=enable-tls1_3`.

Then, your setup may support only TLSv1.3 draft 19, but all the browsers that support TLSv1.3 support only draft 18.

We need to figure out how to get BoringSSL TLSv1.3 draft 18.

**Comment by ghost** [comment] 2017-04-30 23:02
@ajhaydock My nging conf has this line:
```
ssl_protocols TLSv1.3 TLSv1.2;
```
If I compile nginx without the flag, and use the above line, when I start nginx, it craps up. It doesn't like the `TLSv1.3`.

Then I compile nginx with the flag, and use the above line, when I start nginx, it starts fine.

That's all I know.

**Comment by alexhaydock** [comment] 2017-04-30 23:03
@peterkahl The confusing part for me is that when looking at the [current value](https://github.com/google/boringssl/blame/master/include/openssl/ssl.h#L574) in master for the 6-month old draft 18 commit you linked, it still doesn't seem to have changed since then.

I can't imagine BoringSSL _not_ tracking the TLS spec rapidly enough to still be on draft 18 in master, but this line at least seems to suggest it is.

**Comment by alexhaydock** [comment] 2017-04-30 23:05
@peterkahl Interesting. I can get it to start with that config line, but without needing to use the additional flag during compilation. Will do some testing tomorrow to see if I can work it out.

**Comment by ReyKoxha** [comment] 2017-05-01 13:26
I used the compile flag @peterkahl and as @ajhaydock said, the commit you have send us, hasn't changed in a while. This is getting confirmed by https://github.com/tlswg/tls13-spec/wiki/Implementations .

Therefore I assume an issue with the certificate and/or the config file itself.
I will test more ciphers and also try to "minimize" my SSL config, just to get TLS 1.3 running.

**Comment by alexhaydock** [comment] 2017-05-01 14:10
I'm starting to suspect there might be some issue with the `ssl_protocols` directive. When starting Nginx using the following line:
```
ssl_protocols TLSv1.3;
```

I would expect this to _only_ work with TLS 1.3, and for any browser without full support to fail to connect. What I'm seeing, however, is that browsers can still connect and are reporting that a TLS v1.2 connection is being negotiated. Very confusing.

**Comment by ReyKoxha** [comment] 2017-05-01 14:51
Read this:
http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_protocols

> The TLSv1.3 parameter (1.13.0) works only when OpenSSL 1.1.1 built with TLSv1.3 support is used.

Whenever you enter ```nginx -V```, it will return
```
built with OpenSSL 1.0.2 (compatible; BoringSSL) (running with BoringSSL)
```
Therefore I assume that you would need to patch BoringSSL to return OpenSSL 1.1.1.

**Comment by alexhaydock** [comment] 2017-05-01 15:35
This thread seems to have closed itself when I referenced the issue number in a commit. Currently testing a patch to do as you suggested, @ReyKoxha.

**Edit:** Still seems to be defaulting to TLS v1.2 - might need to investigate patching Nginx instead of BoringSSL, since it seems unlikely now that the version string is the only thing determining whether or not to enable v1.3 support.

**Comment by iz8mbw** [comment] 2017-07-17 11:37
Hi.
Any news to enable TLS v1.3 using BoringSSL and nginx?

In my case I have both ECDSA and RSA certificates on "ssl_certificate" and "ssl_trusted_certificate" but ngingx use only the RSA certificate.
More, when I start nginx with BoringSSL I have:

 ``
[....] Starting web server: nginxnginx: [warn] "ssl_stapling" ignored, not supported
nginx: [warn] "ssl_stapling" ignored, not supported
nginx: [warn] "ssl_stapling" ignored, not supported
nginx: [warn] "ssl_stapling" ignored, not supported
nginx: [warn] "ssl_stapling" ignored, not supported
nginx: [warn] "ssl_stapling" ignored, not supported
nginx: [warn] "ssl_stapling" ignored, not supported
nginx: [warn] "ssl_stapling" ignored, not supported
. ok
``

Anyway nginx with BoringSSL use only TLS v1.2.

**Comment by pleaz** [comment] 2018-01-16 14:44
@ajhaydock  do you found solution how to start working tls1.3 with boringssl and nginx ?

**Comment by xetorixik** [comment] 2018-04-10 14:47
@pleaz  found a solution to enable TLS 1.3  (draft 22, 23 and final draft) for the latest BoringSSL + BoringSSL-chromium at https://github.com/cloudflare/sslconfig/issues/87#issuecomment-380125243

**Comment by alexhaydock** [comment] 2018-07-17 00:46
Fixed. Latest commit offers full TLS 1.3 support.

**Closed as completed by alexhaydock** 2018-07-17 00:46 UTC
