### ISSUE TITLE
Unbound variable

### ISSUE THREAD

**Issue by tearfulDalvik** [ajhaydock/BoringNginx#2] opened 2017-03-06 15:04 UTC
This is the screenshot: ![](https://img.ifengge.cn/images/2017/03/06/2017-03-06230359.png)

**Comment by tearfulDalvik** [comment] 2017-03-06 15:18
CentOS 7, And can not specify version too

**Comment by alexhaydock** [comment] 2017-03-06 16:39
I'll see what I can do, but the build script currently only supports Debian. I tried CentOS in the past, but managing the `.spec` files and building the RPMs was a lot of work.

For now, if you're familiar with Docker, you can deploy on CentOS using the [Dockerfile here](https://github.com/ajhaydock/BoringNginx/blob/master/Dockerfile), or [directly from Docker Hub](https://hub.docker.com/r/ajhaydock/boringnginx/).

**Comment by dm-m** [comment] 2017-11-03 05:10
Got the same error on Debian Jessie 8.2 :
./build-debian.sh: line 84: NGXSIGKEY: unbound variable

Is only a Docker image working currently?

**Comment by alexhaydock** [comment] 2018-07-17 00:47
Closing because sadly the bare shell scripts were too destructive and too difficult to maintain. Currently a Docker image is the only supported deployment but provides reproducibility and full TLS 1.3 support.

**Closed as completed by alexhaydock** 2018-07-17 00:47 UTC
